language: java

# 无需root权限
sudo: false

os: linux

jdk:
  - openjdk8

env:
  - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

before_install:
  - sudo apt-get install -y openjfx

# 开启虚拟gui服务
services:
  - xvfb

# 跳过maven完整构建
install: true

# 运行maven测试
script:
  - mvn test