language: java

sudo: false
dist: trusty
os: linux

matrix:
  fast_finish: true
  include:
    - jdk: openjdk8
      if: branch = master
    - jdk: openjdk11
      if: branch = java11

# 跳过maven完整构建
install: true

# 运行maven测试
script: mvn test