language: java

# 无需root权限
sudo: false

os: linux
dist: trusty
jdk: oraclejdk8
env:
  - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi


# 跳过maven完整构建
install: true

# 运行maven测试
script:
  - mvn test