language: java

# 无需root权限
sudo: false

os: linux

matrix:
  fast_finish: true
  include:
    - jdk: openjdk8
      if: branch = master
    - jdk: openjdk11
      if: branch = java11

# 安装openjfx
before_install: sudo apt-get install -y openjfx

# 开启虚拟gui服务
services: xvfb

# 跳过maven完整构建
install: true

# 运行maven测试
script: mvn test